core/urls.py
from .import settings
from django.contrib.staticfiles.urls import static
from django.contrib import admin
from django.urls import path, include
from projects.views import ProjectListView, contactView
from accounts.views import EditView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/edit/", EditView.as_view(), name="edit"),
    path('accounts/', include('allauth.urls')),
    path("", ProjectListView.as_view(), name="project_list"),
    path("projects/", include("projects.urls")),
    path("aiposts/", include("aiposts.urls")),
    path("contact/", contactView, name="contact"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from .views import (ProjectDetailView)
app_name = 'projects' 
urlpatterns = [
    path("<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    # path("<int:pk>/edit/", ProjectUpdateView.as_view(), name="project_edit"),
    # path("<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete"),
    
    # path("new/", ProjectCreateView.as_view(), name="project_new"),
]

projects/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from ckeditor.fields import RichTextField


    
class Project(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    image_path = models.CharField(max_length=1000, blank=True, null=True)
    sub_title = models.CharField(max_length=255, blank=True, null=True)
    sub_title_1 = models.CharField(max_length=255, blank=True, null=True)
    tab_title = models.CharField(max_length=30, blank=True, null=True)
    image = models.ImageField(default='media/placeholders/gallery.jpg')
    description = RichTextField(blank=True, null=True)

    date = models.DateTimeField(auto_now_add=True)
    github = models.URLField(blank=True, null=True)
    youtube = models.URLField(blank=True, null=True)
    udemy = models.URLField(blank=True, null=True)
    link_1 = models.URLField(blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("projects:project_detail", kwargs={"pk": self.pk})


"""
Note that there are two main ways to refer to a custom user model: AUTH_USER_MODEL and get_-
user_model143. As general advice:
• AUTH_USER_MODEL makes sense for references within a models.py file
• get_user_model() is recommended everywhere else such as views, tests, etc.
"""


class Detail(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    code_title = models.CharField(max_length=255, blank=True, null=True)
    code_url = models.URLField(blank=True, null=True)
    code_notes = RichTextField(blank=True, null=True)
    code = RichTextField(blank=True, null=True)


    # user = models.ForeignKey(
    #     settings.AUTH_USER_MODEL,
    #     on_delete=models.CASCADE,
    # )

    def __str__(self):
        return self.project.title

    def get_absolute_url(self):
        return reverse("project:project_list")


class Text(models.Model):

    page_text_1 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_2 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_3 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_4 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_5 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_6 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_7 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_8 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_9 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_10 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_11 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_12 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_13 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_14 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_15 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_16 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_17 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_18 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_19 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_20 = models.CharField(max_length=1000, blank=True, null=True)
    page_text_21 = models.CharField(max_length=1000, blank=True, null=True)
    facebook_url = models.URLField(blank=True, null=True)
    github_url = models.URLField(blank=True, null=True)
    youtube_url = models.URLField(blank=True, null=True)
    linkedin_url = models.URLField(blank=True, null=True)
    text_field_1 = RichTextField(blank=True, null=True)
    text_field_2 = RichTextField(blank=True, null=True)
    text_field_3 = RichTextField(blank=True, null=True)
    text_field_4 = RichTextField(blank=True, null=True)
    def __str__(self):
        return str(self.id)

  

projects/forms.py
from django import forms

class ContactForm(forms.Form):
    # contact_em = forms.CharField(required=True)
    email = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

projects/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Project, Text
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.contrib import messages




def contactView(request):
    text = Text.objects.get(pk=1)
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            # contact_em = form.cleaned_data["contact_em"]
            message = form.cleaned_data["message"]
            try:
                send_mail(message, email, from_email="steve@chesnowitz.com", recipient_list=["steve@chesnowitz.com"]) 
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            messages.add_message(request, messages.INFO, "Your message has been sent.")
            return redirect("/")
    return render(request, "projects/contact.html", {"form": form, "text" : text})




class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/projects_new.html"
    fields = (
        "title",
        "description",
        "github",
    )

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProjectListView(ListView):
    model = Project
    template_name = "projects/project_list.html"
    queryset = Project.objects.order_by("-date")[:6]


    def get_context_data(self, *args, **kwargs):
        context = super(ProjectListView, self).get_context_data(*args, **kwargs)
        context["text"] = Text.objects.get(pk=1)
        return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/project_detail.html"
    extra_context={'text': Text.objects.get(pk=1)}

class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = (
        "title",
        "description",
    )
    template_name = "projects/project_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    template_name = "projects/project_delete.html"
    success_url = reverse_lazy("projects:project_list")

    def test_func(self):
        obj = self.get_object()
        return obj.user == self.request.user

templates/projects/contact.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}




{% include 'contact_form.html' %}

{% endblock content %}

templates/projects/project_delete.html
{% extends "base_main.html" %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ project.title }}"?</p>
<button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/projects/project_detail.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}
<div class="container mt-3">
  <h2>{{ object.title }}</h2>
  <br>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-bs-toggle="tab" href="#home">{{ object.tab_title|safe }}</a>
    </li>
    {% for detail in project.detail_set.all %}
    <li class="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#menu{{ detail.id }}">{{ detail.code_title }}</a>
    </li>
    {% endfor %}
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active">
      <br>
      <h3>{{ object.tab_title|safe }}</h3>
      <p>{{ object.description|safe }}</p>
      <p>
        {% if object.github %}
        <a href="{{ object.github }}" target="_blank">
        <span class='fab fa-github mx-2'></span>
        </a>
        {% endif %}
        {% if object.youtube %}
        <a href="{{ object.youtube }}" target="_blank">
        <span class='fab fa-youtube mx-2'></span>
        </a>
        {% endif %}
        {% if object.link_1 %}
        <a class="px-2 pb-4" href="{{ object.link_1 }}">
        <span><img class="pb-0" src="{% static 'assets/img/linker.svg' %}" width="12" alt=""></span>
        {{ object.link_1 }}
        </a>
        {% endif %}
        {% if object.udemy %}
        <a class="px-2 pb-4" href="{{ object.udemy }}">
        <span><img class="pb-0" src="{% static 'assets/img/udemy.svg' %}" width="12" alt=""></span>
        </a>
        {% endif %}
      </p>
    </div>
    {% for detail in project.detail_set.all %}
    <div id="menu{{ detail.id }}" class="container tab-pane fade">
      <br>
      <h3>{{ detail.code_title }}</h3>
      <p>{{ detail.code|safe }}</p>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/projects/project_edit.html
{% extends "base_main.html" %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
{{ form }}
<button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/projects/project_list.html
{% extends "base_main.html" %}
{% load static %}
{% block title %}projects{% endblock title %}
{% block content %}  
{% include 'about.html' %}  
{% include 'get_it_now.html' %}
<section class="text-center pb-3" id="portfolio">
  <div class="container-fluid">
    <div class="row justify-content-center" data-zanim-timeline="{}" data-zanim-trigger="scroll">
      <div class="col-12 mb-4">
        <div class="overflow-hidden">
          <h2 class="fs-md-5 mb-2" data-zanim-xs='{"duration":1.5,"delay":0}'>
            {{ text.page_text_11}}
          </h2>
        </div>
        <div class="overflow-hidden">
          <p class="fs--1 text-uppercase text-black ls-1 mb-0" data-zanim-xs='{"duration":1.5,"delay":0.1}'>
            {{ text.page_text_12}}
        </p>
        </div>
        <div class="overflow-hidden">
          <hr class="hr-short bg-black opacity-100" data-zanim-xs='{"duration":1.5,"delay":0.2}' />
        </div>
      </div>
    </div>
    <div class="row g-3 mt-3" data-rp-isotope='{"layoutMode":"packery"}'>
      {% for project in project_list %}
      <div class="col-sm-6 col-lg-4 px-2 isotope-item design" data-zanim-xs='{"delay":0}'>
        <div class="hoverdir-item my-0" data-zanim-xs='{"duration":1.5,"animation":"zoom-in","delay":0}'>
          <div class="hoverdir-item-content">
            <a class="d-block" href="{% url 'projects:project_detail' project.id %}">
              <img class="img-fluid rounded" src="{{ project.image_path }}" alt="" />
              <div class="hoverdir-text">
                <h3 class="text-white lh-1 fs-2">{{ project.title }}</h3>
                <p class="ls-1 mb-0 text-700">{{ project.sub_title }}<br>{{ project.sub_title_1 }}</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %} 
    </div>
  </div>
  <!-- end of .container-->
</section>
{% include 'social.html' %}
{% endblock content %}

templates/projects/projects_new.html
{% extends "base_main.html" %}

{% block content %}
<h1>New project</h1>
<form action="" method="post">{% csrf_token %}
{{ form }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}