aiposts/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, SearchResultsView, create_post_view
app_name = 'aiposts' 
urlpatterns = [
    path("new/", create_post_view, name="create_post"),
    path("posts/", PostListView.as_view(), name="post_list"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("search/", SearchResultsView.as_view(), name="search"), 
]

core/urls.py
from .import settings
from django.contrib.staticfiles.urls import static
from django.contrib import admin
from django.urls import path, include
from projects.views import ProjectListView, contactView
from accounts.views import EditView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/edit/", EditView.as_view(), name="edit"),
    path('accounts/', include('allauth.urls')),
    path("", ProjectListView.as_view(), name="project_list"),
    path("projects/", include("projects.urls")),
    path("aiposts/", include("aiposts.urls")),
    path("contact/", contactView, name="contact"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

aiposts/models.py
from django.db import models

from ckeditor.fields import RichTextField

class Post(models.Model):
    title = models.CharField(max_length=2000, blank=True, null=True)
    content = RichTextField(blank=True, null=True)
    url = models.URLField(blank=True, null=True, max_length=3000)
    created_on = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, blank=True, null=True)
    reporter = models.CharField(max_length=1000, blank=True, null=True)
    def __str__(self):
        return self.title

aiposts/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView
from projects.views import Text
from .models import Post
from django.shortcuts import redirect, render
from django.contrib import messages
from django.http import HttpResponseRedirect

# langchain
import os
from langchain.llms import OpenAI
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.document_loaders import WebBaseLoader
from langchain.vectorstores import FAISS
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.callbacks import get_openai_callback
from datetime import datetime

dt = datetime.now()





def create_post_view(request):
    if request.method == "POST":
        if request.POST.get("form_type") == "formOne":
            url = request.POST["url"]
            # print(url)
            context = {"url": url}

            llm = OpenAI(temperature=0.9, verbose=True)

            loader = WebBaseLoader(web_path=url)
            data = loader.load()

            text_splitter = RecursiveCharacterTextSplitter(
                chunk_size=2000, chunk_overlap=250, length_function=len
            )

            docs = text_splitter.split_documents(data)

            embeddings = OpenAIEmbeddings()
            db = FAISS.from_documents(docs, embeddings)
            db.add_documents(docs)

            """
            -------------------------------------------------------------
            Reporter Name
            -------------------------------------------------------------
            """

            prompt_template = """Use the context below to create a ficticious name for a news reporter.
            the name should be less than 25 characters, only generate a full name:
                name: {name}
                context: {query}
                Reporter Name:"""

            story_reporter = PromptTemplate(
                template=prompt_template, input_variables=["name", "query"]
            )

            chain = LLMChain(llm=llm, prompt=story_reporter, verbose=True)

            query = "write a title for the story"
            docs = db.similarity_search(query, k=3)

            story_reporter_name = chain.run({"name": docs, "query": query})
            print(story_reporter_name)
            # num_tokens = llm.get_num_tokens(prompt_template)
            # print (f"Our prompt has {num_tokens} tokens")
            
            

            """
            -------------------------------------------------------------
            Story Title
            -------------------------------------------------------------
            """

            prompt_template = """Use the context below to write  a title.:
                Context: {title}
                Topic: {query}
                Blog title:"""

            title_content = PromptTemplate(
                template=prompt_template, input_variables=["title", "query"]
            )

            chain = LLMChain(llm=llm, prompt=title_content, verbose=False)

            query = "write a title for the story"
            docs = db.similarity_search(query, k=3)
            story_title = chain.run({"title": docs, "query": query})
            print(story_title)
            # callback_token_getter()
            """
            -------------------------------------------------------------
            Story Content
            -------------------------------------------------------------
            """

            prompt_template = """Use the context below to write a 700 word blog post 
            about the context below make sure the story ends with a complete sentence:
                Context: {context}
                Topic: {query}
                Blog post:"""

            prompt_content = PromptTemplate(
                template=prompt_template, input_variables=["context", "query"]
            )

            chain = LLMChain(llm=llm, prompt=prompt_content, verbose=False)

            query = "write a detailed synopsis of this story"
            docs = db.similarity_search(query, k=3)
            story_content = chain.run({"context": docs, "query": query})
            print(story_content)
            # callback_token_getter()
            text = Text.objects.get(pk=1)
            context = {
                "url": url,
                "story_content": story_content,
                "story_reporter_name": story_reporter_name,
                "story_title": story_title,
                "text":text
            }
            
            return render(request, "aipost/create_post.html", context)

        if (
            request.POST.get("form_type") == "formTwo"
            and request.POST.get("story_title")
            and request.POST.get("story_content")
            and request.POST.get("url")
            and request.POST.get("story_reporter_name")
        ):

            post = Post()
            post.title = request.POST.get("story_title")
            post.content = request.POST.get("story_content")
            post.url = request.POST.get("url")
            post.reporter = request.POST.get("story_reporter_name")
            post.save()
            print(post.id)
            messages.success(request, "AI news was successfully created")
                
            return redirect('aiposts:post_detail', post.id)
        else:
            return render(request, "aipost/create_post.html")
           
    text = Text.objects.get(pk=1)
    return render(request, "aipost/create_post.html", {'text':text})


class SearchResultsView(ListView):
    model = Post
    template_name = "aipost/search.html"
    extra_context = {"text": Text.objects.get(pk=1)}
    # def get_context_data(self, *args, **kwargs):
    #     context = super(SearchResultsView, self).get_context_data(*args, **kwargs)
    #     context["text"] = Text.objects.get(pk=1)

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query == "":
            messages.add_message(
                self.request,
                messages.INFO,
                "Your search was blank, please enter a valid search request.",
            )
            redirect("/")
        else:
            object_list = Post.objects.filter(
                Q(content__icontains=query) | Q(title__icontains=query)
            )

            if not object_list.exists():
                messages.add_message(
                    self.request,
                    messages.INFO,
                    "Your search did not return any results.",
                )
            else:
                # print(object_list)
                return object_list


# def search_posts(request):
#     if request.method == Post:
#         search_ai = request.POST('search_ai')
#         context = {'search_ai' : search_ai}
#         print(context)
#         return render(request, 'aipost/search.html', context=context)
#     else:
#         context = {}
#         return render(request, 'aipost/search.html', context=context)


class PostListView(ListView):
    model = Post
    template_name = "aipost/list.html"
    paginate_by = 10
    extra_context = {"text": Text.objects.get(pk=1)}
    ordering = ["-created_on"]

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context["side_page"] = Post.objects.all().order_by("?")[:6]
        context["page_texts"] = Text.objects.get(pk=1)
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "aipost/detail.html"
    extra_context = {"text": Text.objects.get(pk=1)}

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["side_page"] = Post.objects.all().order_by("?")[:6]
        context["page_texts"] = Text.objects.get(pk=1)
        return context

templates/aipost/create_post.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}  








<section>
    <div class="container">
    <h3 class="mt-4 text-transform-none fw-medium">
  
    </h3>
    <div class="row">
      <div class="col-lg-7 mb-4 mb-lg-0">
        <img class="img-fluid rounded" src="../assets/img/blogs/s-3.jpg" alt="" />
        {% if not story_content %} 

        <div class="container">
        <form method=POST action="{% url 'aiposts:create_post' %}" id="formOne">
            <input type="hidden" name="form_type" value="formOne">
            <div class="form-group">
                 {% csrf_token %}   
                <input type="text" name="url" class="form-control" id="url" placeholder="news url">
                <small id="urlHelp" class="form-text text-muted">Enter News URL</small>
              </div>
        
              <button type="submit" class="btn btn-primary">Get News</button>
        </form>
        </div>
        {% endif %} 
        {% if story_content %} 

        <div class="container">
        <form method=POST action="{% url 'aiposts:create_post' %}"id="formTwo">
            <input type="hidden" name="form_type" value="formTwo">
            {% csrf_token %} 
            
            <div class="form-group">
                <input type="hidden" value="{{url}}" name="url" class="form-control" id="url" placeholder="news url">
        
            </div>
            <div class="form-group">
                <label class="form-label">Edit Reporter Name</label>
                <input type="text" value="{{story_reporter_name}}" name="story_reporter_name" class="form-control" id="story_reporter_name" placeholder="reporter name">
          
            </div>
        </br>
            <div class="form-group">
                <label class="form-label">Edit Story Title</label>
                <input type="text" value="{{story_title}}" name="story_title" class="form-control" id="story_title" placeholder="story title">
          
            </div>
        </br>
              <div class="form-group">
                <label class="form-label">Edit Story Content</label>
                <textarea class="form-control" 
                name="story_content" id="story_content" rows="3">{{story_content}}</textarea>
              </div>
            </br>
              <button type="submit" class="btn btn-primary">Save AI News</button>
        </form>
        </div> 
        {% endif %} 
        </div>
        <p></p>
      </div>
      <div class="col-lg-5 ps-lg-7">
        <h4 class="mt-4 mb-3 fw-normal"></h4>
        <div class="d-flex mb-3">
          <div class="flex-1 ms-3">
            <span class="mx-2 text-700">
          
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
    </div>
    <!-- end of .container-->
  </section>


















{% endblock content %} 

templates/aipost/detail.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}  
<section>
  <div class="container">
  <h3 class="mt-4 text-transform-none fw-medium">
    {{ page_texts.page_text_19 }}
  </h3>
  <div class="row">
    <div class="col-lg-7 mb-4 mb-lg-0">
      <img class="img-fluid rounded" src="../assets/img/blogs/s-3.jpg" alt="" />
      <h2 class="mt-4 text-transform-none fw-medium">{{ object.title }}</h2>
      <div class="mb-4"><span class="text-700">{{ page_texts.page_text_19 }} {{ object.reporter }}</span>
        <span class="mx-2 text-700">|</span>
        <span class="text-700">{{ object.created_on }}</span>
        <span class="mx-2 text-700">|</span>
        <a class="text-700" target="_blank" href="{{ object.url }}">{{ page_texts.page_text_20 }}</a>
        <span class="mx-2 text-700">|</span>
        <a class="text-700" href="{% url 'aiposts:post_list' %}">
        Latest Stories
        </a>
      </div>
      <p>{{ object.content|safe }}</p>
    </div>
    <div class="col-lg-5 ps-lg-7">
      <h4 class="mt-4 mb-3 fw-normal">{{ page_texts.page_text_18 }}</h4>
      <div class="d-flex mb-3">
        <div class="flex-1 ms-3">
          <span class="mx-2 text-700">
          {{ page_texts.text_field_1|safe }}
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
  </div>
  <!-- end of .container-->
</section>
{% endblock content %}

templates/aipost/list.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}  
<section>
  <div class="container">
    <div class="row">
        {{ page_texts.text_field_2|safe }}
      <div class="col-lg-7">
        {% for aipost in object_list %}
        <div class="mb-6">
          <a href="{% url 'aiposts:post_detail' aipost.id %}">
            <h4 class="font-base text-transform-none fw-medium lh-2 mt-3">
          <a class="text-black" href="{% url 'aiposts:post_detail' aipost.id %}">
          {{ aipost.title }}
          </a>
          </h4>
          <div class="mb-3">
            By Fake AI: 
            <a class="text-700">{{ aipost.reporter }}</a>
            <span class="mx-2 text-700">|</span>
            <a class="text-700">{{ aipost.created_on }}</a>   
            <span class="mx-2 text-700">|</span>
            <a class="text-700" target="_blank" href="{{ aipost.url }}">Original Story</a>
          </div>
          <p>{{ aipost.content|truncatechars:350|safe }}</p>
          <a class="text-dark fw-semi-bold" href="{% url 'aiposts:post_detail' aipost.id %}">Read more
          <span class="fas fa-angle-right ms-1 text-900" data-fa-transform="down-2"></span>
          </a>
        </div>
        {% endfor %}
        <div class="col-12 p-0">
          <div class="d-flex mt-7">
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-rounded">
                {% if is_paginated %}
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span class="fas fa-angle-left"></span>
                    </a>
                  </li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                  <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                  {% endfor %}
                  {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span class="fas fa-angle-right"></span>
                    </a>
                  </li>
                  {% endif %}
                </ul>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-lg-5 ps-lg-7">
        <form class="d-flex" role="search" method="get" action="{% url 'aiposts:search' %}">
          {% csrf_token %} 
          <input name="q" class="form-control me-1" type="search" placeholder="Search AI News" aria-label="Search">
          <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
        <h4 class="mt-4 mb-3 fw-normal">{{ page_texts.page_text_17}}</h4>
        {% for post in side_page %}
        <div class="d-flex mb-3">
          <div class="flex-1 ms-3">
            <h5 class="lh-sm mt-0 text-transform-none fs-0 mb-1 fw-semi-bold font-base">
              <a class="text-900" href="{% url 'aiposts:post_detail' post.id %}">
              {{ post.title }}
              </a>
            </h5>
            <p class="text-600 mb-0">{{ post.created_on }}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <!-- end of .container-->
</section>
<!-- <section> close ============================-->
<!-- ============================================-->
{% endblock content %}

templates/aipost/search.html
{% extends "base_main.html" %}
{% load static %}
{% block content %}  
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg pe-lg-5 mb-4 mb-lg-0 position-relative">
        <p>
          {% if object_list == None %}
        <h3>No Results</h3>
        {% endif %}
        {% if object_list %}
        <h3>Your search results...</h3>
        <ul>
          {% for post in object_list %}
          <li>
            <a href="{% url 'aiposts:post_detail' post.id %}">
            {{ post.content|truncatechars:50 }}</a>
          </li>
          </br>
          {% endfor %}
        </ul>
        {% endif %}        </p>
        <div class="vertical-line"></div>
      </div>
    </div>
  </div>
  <!-- end of .container-->
</section>
{% endblock content %}